language: node_js
node_js:
- '0.10'
before_script:
- chmod +x .travis/after_success.sh
env:
  global:
  - REPO="git@github.com:g0v/etax-gitbook"
  - secure: dCn5gWVkwa8adfWHfS+z+6o7VyCjXC7pHnyaa+kLWZaZuphKZtloWkfKfW2CdBzImwIPfkCUaEGGKZ49ZddfwYREcy19D6dDWGBy4pBMu5zlBtDbx/JdmdX2hxgOmzCPNSDjLVocxkZyucM9CHFii83ZIHdD7dkNmPCVn3jk0SY=
after_success: ".travis/after_success.sh"
